# Generated by Django 3.1.4 on 2020-12-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('var_a', models.IntegerField(default=0)),
                ('var_b', models.IntegerField(default=0)),
                ('addd', models.IntegerField(default=0)),
            ],
        ),
    ]
